Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -66,12 +66,20 @@ jobs:
         kubectl apply -f k8s/deployment.yaml
         kubectl apply -f k8s/service.yaml
         kubectl apply -f k8s/ingress.yaml
-
     - name: Install ALB Ingress Controller
       run: |
-        helm repo add eks https://aws.github.io/eks-charts
-        helm repo update
-        helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller           --set clusterName=dev-eks           --set serviceAccount.create=false           --set serviceAccount.name=aws-load-balancer-controller           -n kube-system
+         kubectl get deployment -n kube-system aws-load-balancer-controller || echo "Controller not found, proceeding with install"
+    
+         helm repo add eks https://aws.github.io/eks-charts
+         helm repo update
+
+         helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
+           -n kube-system \
+           --set clusterName=dev-eks \
+           --set serviceAccount.create=false \
+           --set serviceAccount.name=aws-load-balancer-controller \
+           --set region=us-west-2 \
+           --set vpcId=vpc-01e122b5d6e1ff11d
 
     - name: Install Prometheus and Grafana
       run: |
